### ISSUE TITLE
Uncaught Exception in ControlCenter and Sitemap

### ISSUE THREAD

**Issue by kersten** [mblaschke/TYPO3-metaseo#189]
Hi,

I've get the following error if I try to open the backend controlcenter or sitemap:

```
Uncaught TYPO3 Exception
#1285067843: A back-end form protection may only be instantiated if there is an active back-end session.
```

Here is the complete exception: http://pastebin.com/njivaMNy

I'm using 7.6.2 and PHP7 and latest develop of metaseo.

**Comment by thomaszbz** [comment]
Thanks for reporting this. Could be PHP7 related (which indeed is supported by TYPO3 CMS 7.6). @mblaschke We'll also have to test against PHP7 then.

@kersten Could you please try again and thereby make absolutely sure that you are logged in in the backend? Does the problem occur sometimes only or can you reproduce it every time you try?

[Current develop: 2c064fed3bd90aa5550bacbc65d99c203eceef62]

**Comment by kersten** [comment]
@thomaszbz I am absolutely sure that I am logged in :) The problem occurs on every click on the two buttons.

![image](https://cloud.githubusercontent.com/assets/487289/12141869/b807e7da-b473-11e5-976a-53e57543e8ee.png)

But just after checking again, it was working?!? I've only made some minor changes to ```Backend/Module/AbstractModule.php```

![image](https://cloud.githubusercontent.com/assets/487289/12141934/3b195e42-b474-11e5-8313-d93827e34f0b.png)

**Comment by thomaszbz** [comment]
There was a recent change for 7.6 compatibility: 962a4ba24fdfa2bb1983d57de53bc6ca5152bcec

Indeed, the FQDN should get removed, but nevertheless does not hurt in PHP 5.x.

To sum it up: The error occurs without the change and disappears with the change applied, both in a reproducable manner? Please make sure you clear caches in between.

**Comment by kersten** [comment]
This is strange the error does not occur if I am reverting the changes. For sure I cleaned the caches, and I definitely  logged out and logged back in again before posting the complete issue.

Cleaned the caches too.

The only thing I remember was turning beta function on and off again. But that would be really strange if this had fixed it.

**Comment by thomaszbz** [comment]
Is your TYPO3 7.6 LTS a fresh install or did you upgrade from an earlier version (e.g. 6.2 LTS)?

As long as everything works please let us know if the error occurs again. We'll track the issue and we'll see if other users are affected as well or if we can reproduce it ourselves.

**Comment by mblaschke** [comment]
Is the TYPO3 in composer mode?

**Comment by kersten** [comment]
@thomaszbz it was an upgrade from the last 6 LTS version. I will immediately report here if i get the error again.

@mblaschke no, it is not in composer mode

**Comment by thomaszbz** [comment]
Could you please describe the update steps in chronological order you were performing? When did you see the error for the very first time?

E.g. something like

- Install PHP 5.x, TYPO3 6.2 LTS
- Install metaseo 1.0.x
- Update to PHP7
- Update TYPO3 7.6 LTS
- cleared caches
- Update to metaseo develop (or did you perform a fresh install of metaseo here?)
- cleared caches
- => Error occured for the very first time
- cleared caches
- Error disappeared

Did you uninstall metaseo somewhere in between?
Which was your cache clearing procedure? Did you include the orange button? Did you include cache-clearing from the install tool?
Did you toggle between TYPO3's debug/production mode?

**Comment by thomaszbz** [comment]
@kersten Could you solve this issue? What was the solution?

Did the problem reappear? Can I close this issue or could it still affect other users (maybe you just somehow worked around it)?

**Comment by clicsoft** [comment]
Hi there, we have the same problems with Typo3 7.6.6 and metaseo 2.0.0:
Not one backend module of can be opened since this error :-(

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1285067843: A back-end form protection may only be instantiated if there is an active back-end session. | TYPO3\CMS\Core\Error\Exception thrown in file /home/httpd/vhosts/xxxxx/httpdocs/typo3_src-7.6.6/typo3/sysext/core/Classes/FormProtection/BackendFormProtection.php in line 104. Requested URL: http://www.xxxx.ch/typo3/index.php?M=web_MetaseoPageseo&moduleToken=1324f3a24c6f3e4e5a37e28ad90558022f622f44&id=703&`

**Comment by thomaszbz** [comment]
@clicsoft Please follow the steps which were already mentioned. I could not reproduce it because the original reporter can't reproduce which step finally helped.

That's also my experience with TYPO3-updates: Clear all the caches multiple times, play around, and at some point the magic happens and everything works (without any change...).

Did the problem occur after you updated from 6.2 to 7.6.6?

**Comment by clicsoft** [comment]
@thomaszbz Yes we did upgrade. But not to 7.6.6 - to 7.6.1. I think that sometimes it really worked. Otherwise we wouldn't have use for this. Now it doesn't work anymore. 
Sorry don't have time to play around. Did now cleared alle caches and system cache for about 30 times. No success :-(

**Comment by thomaszbz** [comment]
Can you try to clear caches and php opcode cache in the install tool?

Please click the corresponding install tool buttons multiple times and in multiple order. It sounds strange, but I experienced myself multiple times that this can help.

In case you cannot access the install tool via backend, you still can access it with the install tool's direct url ``www.example.com/typo3/install``

**Comment by clicsoft** [comment]
We already tried it with manually clearing all file and datebase-caches, within typo3 backend and within Install Tool. Nothing worked.

**Comment by thomaszbz** [comment]
@kersten Could you please help out? Maybe you can tell us your solution?

@clicsoft Do you want to manually test the FQDN refactoring which @kersten provided?

**Comment by clicsoft** [comment]
@thomaszbz OK, will have a look soon.

**Comment by thomaszbz** [comment]
Btw, are you using PHP7 like @kersten?

**Comment by clicsoft** [comment]
Nope, PHP 5.6

**Comment by clicsoft** [comment]
@thomaszbz Sorry Thomasz, I have no time at all to dig in any further at the moment. 
Maybe I'll have a chance later after summer months.

**Comment by kersten** [comment]
Sorry guys for not responding to this in the last days. @thomaszbz I was using PHP7 but after not getting other extensions to work, I switched back to PHP5.6.

I can't remember what finally helped, but testing if the FQDN fix would be nice to see if this fixes the error.

I've fixed a lot of other extensions and tested out some stuff with PHP7 but never got this error with other exts. And from now on I only build composer mode TYPO3 sites.

I could test this in the next days again with PHP7 if that would help.

**Comment by thomaszbz** [comment]
Found a bunch of namespaces to be imported via #252.

Still, this issue is not reproduced as a bug as it rather looks like a caching issue.

If someone get's this error again with f727717cc7816db95d09c105085164cde177cadd and later (2.0.1 as soon as we release it), please report back that you still get this error.

Technically, f727717cc7816db95d09c105085164cde177cadd will not fix this issue as importing namespaces is only a syntactical change with (theoretically) same behaviour.

Refactoring took place via #252, therefore removing the refactoring tag.

**Comment by thomaszbz** [comment]
There's a bugfix in the pipeline which affects 7.6.10:

https://forge.typo3.org/issues/76995
https://review.typo3.org/48379

The patch is not merged yet, so the corresponding -dev branches will not contain it yet.

If it fixes this issue in the core, it's invalid for metaseo.

Folks affected by this issue, please make sure that forge-issue 76995 makes it into 7.6.11 and use 7.6.11. If you are still affected after that, please report back.

**Comment by thomaszbz** [comment]
@kersten @clicsoft Are you still affected by this issue with 7.6.11+? I have not heared someone complaining on this for a long time. They also merged forge-76995 a long time ago.

If the issue still exists, please report back and I reopen it.
